firstNum = input("Enter your first number: ")
firstNum = int(firstNum)
secondNum = input("Enter your second number: ")
secondNum = int(secondNum)
print("The sum of your two numbers is ",firstNum + secondNum)